Remove extraneous whitespace in debug instructions
The parameter is --verbose.  Passing '-- verbose' causes verbose to be
passed as an argument (instead of an option) and the following error to
be emitted:

    error: unrecognized arguments: -- verbose